# Theme 
foreground #a9b1d6
background #1a1b26

# Noir
color0 #15161e
color8 #414868

# Rouge
color1 #f7768e
color9 #f7768e

# Vert
color2  #9ece6a
color10 #9ece6a

# Jaune
color3  #e0af68
color11 #e0af68

# Bleu
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# Blanc
color7  #a9b1d6
color15 #c0caf5

# ===============================================
# Transparence                                  =
# ===============================================
background_opacity 0.95
background_blur 20

# ===============================================
# Font                                          =
# ===============================================
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic

font_size 11.0

# Ligature
disable_ligatures never

# ===============================================
# Retirer la barre windows
# ===============================================
remember_window_size yes
initial_window_width 1200 
initial_window_height 800

window_padding_width 4 
placement_strategy center 

hide_window_decorations yes 

# ===============================================
# TABS 
# ===============================================
# Barre en haut (ou "bottom" pour en bas)
tab_bar_edge top

# Style moderne
tab_bar_style powerline

# Effet incliné
tab_powerline_style slanted

# Affiche TOUJOURS la barre (même avec 1 tab)
tab_bar_min_tabs 1

# Marges de la barre
tab_bar_margin_height 0.0 0.0
tab_bar_margin_width 0.0

# Couleurs des tabs (Tokyo Night)
active_tab_foreground   #1f2335
active_tab_background   #7aa2f7
inactive_tab_foreground #787c99
inactive_tab_background #1f2335

# Affiche le numéro et le titre du tab
tab_title_max_length 30
tab_title_template "{index}: {title}"
