# Theme 
foreground #a9b1d6
background #1a1b26

# Noir
color0 #15161e
color8 #414868

# Rouge
color1 #f7768e
color9 #f7768e

# Vert
color2  #9ece6a
color10 #9ece6a

# Jaune
color3  #e0af68
color11 #e0af68

# Bleu
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# Blanc
color7  #a9b1d6
color15 #c0caf5

# ===============================================
# Transparence                                  =
# ===============================================
background_opacity 0.95
background_blur 20

# ===============================================
# Font                                          =
# ===============================================
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
bold_italic_font FiraCode Nerd Font Bold Italic

font_size 11.0

# Ligature
disable_ligatures never