# ================================================
# Raccourcis clavier GNOME                      ==
# ================================================

# Terminal Kitty 
Kitty Terminal|kitty|<Super>t

# Codium 
VSCodium|flatpak run com.vscodium.codium|<Super>c

# Gestionnaire de fichier 
Files|nautilus|<Super>e

# Navigateur 
Brave Browser|brave-Browser|<Super>b
